class CRMClientUpdate(object):
    SAVE_CITY_BUTTON = "save_city_button"
    EDIT_CITY_FIELD = "edit_city_field"
    CITY_ELEMENT = "city_element"
    SAVE_POST_CODE_BUTTON = "save_post_code_button"
    EDIT_POST_CODE_FIELD = "edit_post_code_field"
    POST_CODE_ELEMENT = "post_code_element"
    SAVE_CITIZEN_BUTTON = "save_citizen_button"
    PHONE_ELEMENT = "phone_element"
    FIRST_NAME_ELEMENT = "first_name_element"
    LAST_NAME_ELEMENT = "last_name_element"
    EDIT_FIRST_NAME_FIELD = "edit_first_name_field"
    EDIT_LAST_NAME_FIELD = "edit_last_name_field"
    EDIT_PHONE_FIELD = "edit_phone_field"
    SAVE_FIRST_NAME_BUTTON = "save_first_name_button"
    SAVE_LAST_NAME_BUTTON = "save_last_name_button"
    SAVE_PHONE_BUTTON = "save_phone_button"
    CLIENT_UPDATE_CRM = "client_update_crm"
