class AuditLogsConstants(object):
    FIRST_EMAIL = "first_email"
    FIRST_USER_AGENT = "first_user_agent"
    FIRST_ID_RECORD = "first_id_record"
    FIRST_USER = "first_user"
    FIRST_TAB = "first_tab"
    SECOND_TAB = "second_tab"
    THIRD_TAB = "third_tab"
    FOURTH_TAB = "fourth_tab"
    AUDIT_LOGS_MODULE = "Audit Logs"
    AUDIT_LOGS_MODULE_INFO = "Audit_Logs_module_info"
    FIRST_MODULE = "first_module"
    FIRST_ACTION = "first_action"
    MODULE_USERS = "Users"
    ACTION_1 = "OTP: Authenticate, Login Success"
