class CRMMassEditConstants(object):
    USER_ONE = "Panda Support"
    DEPARTMENT_OTHER = "0"
    GENDER_MALE = "gender_male"
    GENDER_FEMALE = "gender_female"
    ASSIGNED_TO_PANDA = "assigned_to_panda"
    CLIENT_SOURCE = "client_source"
    COMPLIANCE_AGENT = "compliance_agent"
    COMPLIANCE_NOTES = "compliance_notes"
    CLIENT_STATUS = "client_status"
    RETENTION_STATUS = "retention_status"
    DESCRIPTION = "description"
    REFERRAL = "referral"
    MASS_EDIT_ONE = "mass_edit_1"
