class FinancialTransactionsModuleConstants(object):
    FIRST_TAB = "first_tab"
    SECOND_TAB = "second_tab"
    THIRD_TAB = "third_tab"
    THIRD_TAB_LOWERCASE = "third_tab_lowercase"
    FOURTH_TAB = "fourth_tab"
    FOURTH_TAB_LONG = "fourth_tab_long"
    FIFTH_TAB = "fifth_tab"
    SIX_TAB = "six_tab"
    SIX_TAB_LONG = "six_tab_long"
    FINANCIAL_TRANSACTIONS_MODULE = "Financial Transactions"
