class TradingAccountConstants(object):
    TRADING_ACCOUNT_MODULE_TABS = "TradingAccountModuleTabs"
    TRADING_ACCOUNT_MODULE_COLUMNS = "TradingAccountModuleColumns"
    FILTER_NAME = "filter_name"
    FIRST_COLUMN = "first_column"
    SECOND_COLUMN = "second_column"
    THIRD_COLUMN = "third_column"
    FOURTH_COLUMN = "fourth_column"
    FIFTH_COLUMN = "fifth_column"
    SIXTH_COLUMN = "sixth_column"
    SEVENTH_COLUMN = "seventh_column"
    EIGHTH_COLUMN = "eighth_column"
    FIRST_TAB = "first_tab"
    SECOND_TAB = "second_tab"
    THIRD_TAB = "third_tab"
    FOURTH_TAB = "fourth_tab"
    FIFTH_TAB = "fifth_tab"
