test = "Regression New Forex Staging"
timeout = 4
data = None
url_client_area = "https://newforexqa.pandats.com/"
url_crm = "Regression New Fore Staging"
url_gmail = "https://mail.google.com"
window_after = None
window_before = None
counter = 1
logger = None
handler = None
