test = "New Forex production sanity"
timeout = 4
data = None
url_client_area = ""
url_crm = ""
url_gmail = "https://mail.google.com"
window_after = None
window_before = None
counter = 1
logger = None
handler = None
chrome_driver = "/usr/lib/chromium-browser/chromedriver"
