# ATTENTION! KEEP NAMES OF PAGES IN ALPHABETICAL ORDER
FinancialTransactionsPage:
  client_name_element: "(//*[@id='listBody']//tr/td[3])[%s]"
  transaction_type_drop_down: "//td[6]/div/div[1]/button"
  transaction_type_element: "(//*[@id='listBody']//tr/td[6])[%s]"
  modified_time_element: "(//*[@id='listBody']//tr/td[10])[%s]"
LeadViewInfo:
  convert_lead_module: "//div[@id='sidebar']//tr[3]//a"
ClientProfilePage:
  deposit_sum: "//tr[@class='lvtColData'][1]//td[3]"
  credit_in_sum: "//*[@id='rld_table_content']/tbody/tr[2]/td[6]/span[1]"
ClientsPage:
  id_client: "//a[contains(text(), 'ACC')]"
LeadDetailViewInfo:
    referral: "//td[contains(text(),'Refferal')]//following-sibling::td[1]"