# ATTENTION! KEEP NAMES OF PAGES IN ALPHABETICAL ORDER
FinancialTransactionsPage:
  client_name_element: "(//*[@id='listBody']//tr/td[3])[%s]"
  transaction_type_drop_down: "//td[6]/div/div[1]/button"
  transaction_type_element: "(//*[@id='listBody']//tr/td[6])[%s]"
  modified_time_element: "(//*[@id='listBody']//tr/td[10])[%s]"
  tab: "//li[contains(text(),'Credit Out')]"
  demo_tab: "//li[contains(text(),'Demo Accounts Transactions')]"
  deposits_tab: "//li[contains(text(),'Deposits')]"
  withdraw_tab: "//li[contains(text(),'Withdraw')]"
  trading_account_element: "(//*[@id='listBody']//tr/td[3])[%s]//a"
LeadViewInfo:
  convert_lead_module: "//div[@id='sidebar']//tr[3]//a"
CRMClientDeposit:
  i_confirm_checkbox: "//*[@name='confirm']"
ClientProfilePage:
  deposit_sum: "//tr[@class='lvtColData'][1]//td[3]"
  credit_in_sum: "//*[@id='rld_table_content']/tbody/tr[2]/td[6]/span[1]"
  i_confirm_checkbox: "//*[@name='confirm']"
  choose_account_drop_down: "//*[@id='ClientDepositConfirmation']//button[@title='Choose trading account']"
  choose_number: "//span[contains(text(), '%s')]"
ClientsPage:
  id_client: "//a[contains(text(), 'ACC')]"
  country: "//*[@id='customAdvanceSearch']/td[6]/div/div[1]/button"
  country_input: "//*[@id='customAdvanceSearch']/td[6]/div/div[1]/ul/li[1]/div/input"
LeadDetailViewInfo:
    referral: "//td[contains(text(),'Refferal')]//following-sibling::td[1]"
TasksPage:
  edit_event: "/html/body/app-root/tasks-list/div/div[2]/div/grid/div[2]/div/div[1]/table/tbody/tr[2]/td[18]/div[5]/div/span"
  subject_button: "/html/body/app-root/tasks-list/div/div[2]/div/grid/div[2]/div/div[1]/table/tbody/tr[1]/td[3]/filters-factory/multiple-select-bs-filter/filter-multiple-select-bs/div/ss-multiselect-dropdown/div/button"
  subject_field: "/html/body/app-root/tasks-list/div/div[2]/div/grid/div[2]/div/div[1]/table/tbody/tr[1]/td[3]/filters-factory/multiple-select-bs-filter/filter-multiple-select-bs/div/ss-multiselect-dropdown/div/ul/li[1]/div/input"
  event_type: "/html/body/app-root/tasks-list/div/div[2]/div/grid/div[2]/div/div[1]/table/tbody/tr[1]/td[3]/filters-factory/multiple-select-bs-filter/filter-multiple-select-bs/div/ss-multiselect-dropdown/div/ul/li[5]/a/input"
CALoginPage:
  sign_up: "//*[@id='dnn_ctr517_Login_Login_DNN_registerLink']"
  country_registr: "//select[@id = 'ddlCountries']"
  select_country: "//*[@id='ddlCountries']/option[contains(text(), '%s')]"
  first_name: "//*[@id='dnn_ctr480_View_txtFirstName']"
  last_name: "//*[@id='dnn_ctr480_View_txtLastName']"
  phone: "//input[@class = 'phone_number']"
  password: "//*[@id='dnn_ctr480_View_txtPassword']"
  confirm_password: "//*[@id='dnn_ctr480_View_txtConfirmPassword']"
  terms_conditions: "//*[@id='chbAgreeWithTerms']"
  submit: "//*[@id='btnSubmit']"
  email: "//*[@id='dnn_ctr480_View_txtEmail']"
  phone_area: "//input[@class = 'phone_area_code']"
  city: "//*[@id='cty']"
  zip_code: "//*[@id='zip']"
  address: "//*[@id='addr1']"
  check_box_2: "//*[@id='GDPR']"
