# ATTENTION! KEEP NAMES OF PAGES IN ALPHABETICAL ORDER
ClientsPage:
  client_status_button: "//tr[@id='customAdvanceSearch']//td[3]//span[@class='multiselect-selected-text']"
  client_status_field: "//tr[@id='customAdvanceSearch']//td[3]//input[@class='form-control multiselect-search']"
  country_button: "//tr[@id='customAdvanceSearch']//td[8]//span[@class='multiselect-selected-text']"
  country_field: "//tr[@id='customAdvanceSearch']//td[8]//input[@class='form-control multiselect-search']"
  country_click: "//label[contains(text(),'%s')]"
TasksPage:
  pencil_button: "/html/body/app-root/tasks-list/div/div[2]/div/grid/div[2]/div/div[1]/table/tbody/tr[2]/td[18]/div[5]/div/span"
  subject_input: "//tr[@class='tableFilters']//td[15]//input"
  account_name_input: "//*[@id='host-element']/input"
FinancialTransactionsPage:
  client_name_element:  "(//td[3]/div/a)[%s]"
  transaction_type_element : "(//*[@id='listBody']//tr/td[5])[%s]"
  transaction_type_field: "(//div/div[1]/ul/li[1]/div/input)[1]"
  transaction_type_drop_down: "//td[5]/div/div[1]/button"
  trading_account_element: "(//*[@id='listBody']//tr/td[3])[%s]//a"
  modified_time_element: "(//*[@id='listBody']//tr/td[10])[%s]"
ClientProfilePage:
  deposit_sum: "//tr[@class='lvtColData'][1]//td[3]"
  i_confirm_checkbox: "//*[@name='confirm']"
  email: "//td[contains(text(),'Email')]//following-sibling::td[1]"
CRMClientDeposit:
  i_confirm_checkbox: "//*[@name='confirm']"
AffiliatePage:
  countrys: "//span[contains(@class,'hovered-option')][contains(text(),'%s')]"
  methods: "//span[@class = 'hovered-option ng-star-inserted'][contains(text(),'%s')]"
  button_plus: "//div[@class='form-group']/button[@class='btn btn-primary']"
  methods_drop_down: "(//span[@class='ng-star-inserted' and contains(text(),'elected')])[1]"
  input_methods: "(//span[@class='filter-search-container active-option']/input[@placeholder='Search...'])[1]"
  blocked_country_drop_down: "(//span[@class='ng-star-inserted' and contains(text(),'elected')])[2]"
  input_country: "//div[@class='select-options options-enabled']//input[@placeholder='Search...']"
  trash_button: "//span[@class = 'glyphicon glyphicon-trash cursor-pointer ng-star-inserted']"
LeadsModule:
  check_first_line_email_1: "//tbody[@id = 'listBody']/tr[1]/td[9]"
  check_first_line_email_2: "//tbody[@id = 'listBody']/tr[2]/td[9]"
  check_first_line_exist: "//tbody[@id = 'listBody']/tr[1]/td[11]"
  check_first_line_leads_no1: "//tbody[@id = 'listBody']/tr[1]/td[3]"
  check_first_line_leads_no2: "//tbody[@id = 'listBody']/tr[2]/td[3]"
  edit_status: "//*[@id='leadstatus_mass_edit_check']/div[1]/div"
  mass_edit_leads: "//*[@id='list_action_buttons']/input[2]"