# ATTENTION! KEEP NAMES OF PAGES IN ALPHABETICAL ORDER
ClientsPage:
  client_status_button: "//tr[@id='customAdvanceSearch']//td[3]//span[@class='multiselect-selected-text']"
  client_status_field: "//tr[@id='customAdvanceSearch']//td[3]//input[@class='form-control multiselect-search']"
  country_button: "//tr[@id='customAdvanceSearch']//td[8]//span[@class='multiselect-selected-text']"
  country_field: "//tr[@id='customAdvanceSearch']//td[8]//input[@class='form-control multiselect-search']"
  country_click: "//label[contains(text(),'%s')]"
  client_currency: "//td[@class='dvtCellInfo'][contains(text(),'EUR')]"
  client_phone: "//div[@title='Click to Call'][@class='actions_btn']"
  client_country: "//span[@id='dtlview_Country']"
TasksPage:
  pencil_button: "/html/body/app-root/tasks-list/div/div[2]/div/grid/div[2]/div/div[1]/table/tbody/tr[2]/td[18]/div[5]/div/span"
  subject_input: "//tr[@class='tableFilters']//td[15]//input"
  account_name_input: "//*[@id='host-element']/input"
FinancialTransactionsPage:
  client_name_element:  "(//td[3]/div/a)[%s]"
  transaction_type_element : "(//*[@id='listBody']//tr/td[5])[%s]"
  transaction_type_field: "(//div/div[1]/ul/li[1]/div/input)[1]"
  transaction_type_drop_down: "//td[5]/div/div[1]/button"
  trading_account_element: "(//*[@id='listBody']//tr/td[3])[%s]//a"
  modified_time_element: "(//*[@id='listBody']//tr/td[10])[%s]"
ClientProfilePage:
  deposit_sum: "//tr[@class='lvtColData'][1]//td[3]"
  i_confirm_checkbox: "//*[@name='confirm']"
  email: "//td[contains(text(),'Email')]//following-sibling::td[1]"
CRMClientDeposit:
  i_confirm_checkbox: "//*[@name='confirm']"
AffiliatePage:
  countrys: "//span[@class = 'hovered-option'][contains(text(),'%s')]"
  methods: "//span[@class = 'hovered-option ng-star-inserted'][contains(text(),'%s')]"
  button_plus: "/html/body/bs-modal[2]/div/div/form/bs-modal-body/div/div[3]/button"
  methods_drop_down: "/html/body/bs-modal[2]/div/div/form/bs-modal-body/div/div[5]/div[2]"
  input_methods: "/html/body/bs-modal[2]/div/div/form/bs-modal-body/div/div[5]/div[2]/filter-multi-select/div/div[2]/span[1]/input"
  blocked_country_drop_down: "/html/body/bs-modal[2]/div/div/form/bs-modal-body/div/div[6]/div[2]"
  input_country: "/html/body/bs-modal[2]/div/div/form/bs-modal-body/div/div[6]/div[2]/filter-multi-select/div/div[2]/span[1]/input"
CALoginPage:
  sign_up: "//button[contains(text(), 'Sign Up')]"
  check_box_accept: "//span[contains (text(), 'Terms and Conditions')]"
  login_btn: "//button[contains(text(), 'Login')]"
  citizenship: "//custom-select[@name='citizenship']//span[text()='%s']"
  submit_btn: "//button[contains (text(), 'Submit')]"
  login_email_input: "//input[@name='login']"
  login_btn_2: "//button[@class = 'forex-button-pandats login-button-pandats'][contains(text(), 'Login')]"
  input_first_name: "//input[@name = 'firstName']"
  input_last_name: "//input[@name = 'lastName']"
  input_confirm_password: "//input[@name = 'passwordConfirm']"
  city: "//input[@name = 'city']"
  address: "//input[@name = 'address']"
  zip_code: "//input[@name = 'postCode']"
  next_btn: "//button[contains (text(), 'Next')]"